version: '3' #definindo qual a versão do docker vamos utilizar

services: 
  app:
    container_name: app
    restart: always
    build: . # . significa que a dockerfile vai estar na pasta raiz do nosso projeto
    ports:
      - '3000:3000' # a porta que a aplicação vai rodar
    links:
      - mongo
    volumes:
      - .:/usr/app # a pasta que vamos monitorar


  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'